// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: esp32_7inch

#include "../ui.h"

void ui_comp_Image1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Image2_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Image4_create_hook(lv_obj_t * comp)
{
}
