// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: esp32_7inch

#ifndef _ESP32_7INCH_UI_COMP_HOOK_H
#define _ESP32_7INCH_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Image1_create_hook(lv_obj_t * comp);
void ui_comp_Image2_create_hook(lv_obj_t * comp);
void ui_comp_Image4_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
