// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: esp32_7inch

#include "ui.h"

void nockanda(lv_event_t * e)
{
	// Your code here
}

void nockanda2(lv_event_t * e)
{
	// Your code here
}
